name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.1'
          channel: 'stable'

      - run: flutter pub get

      - run: flutter build web --release --base-href "/cringe/" --no-web-resources-cdn

      - name: Fix canvaskit path in flutter_bootstrap.js
        run: |
          sed -i 's|"/canvaskit/"|"/cringe/canvaskit/"|g' build/web/flutter_bootstrap.js

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web